### ISSUE TITLE
npm ERR! 404 Not Found: @baidu/events-emitter@1.0.15

### ISSUE THREAD

**Issue by wange1228** [swan-team/swan-core#4]
package.json 中有一个依赖是 `@baidu/events-emitter`，官方 npm 源中没有这个包

**Comment by tbjgod** [comment]
2123 silly saveTree @super-fe/swan-core@2.3.2
2123 silly saveTree ├── babel-plugin-istanbul@4.1.6
2123 silly saveTree ├── fs-finder@1.8.1
2123 silly saveTree ├── karma-spec-reporter@0.0.32
2123 silly saveTree └── san@3.6.15
