### ISSUE TITLE
如何使已有APP获得智能小程序的能力？

### ISSUE THREAD

**Issue by fpl1104** [swan-team/swan-core#5]
如何把智能小程序接入已有APP？

**Comment by houyu01** [comment]
你说的是在自己的APP中集成小程序的SDK么？

**Comment by WZTENG** [comment]
如何在APP中集成小程序的SDK？是否有相关文档，或者DEMO？

**Comment by houyu01** [comment]
目前还处于内测阶段，请登录开源官网填写申请表
https://smartprogram.baidu.com/developer/opensource.html

**Comment by chenggoi** [comment]
只根据swan-core可以将自己的app改造成小程序的载体吗？
